/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Email } from "./email/service";
import { IconDefinition } from "@fortawesome/fontawesome-svg-core";
export namespace Components {
    interface AppHeader {
    }
    interface AppHome {
    }
    interface AppProfile {
        "name": string;
    }
    interface AppRoot {
    }
    interface CheckBox {
        "value": boolean;
    }
    interface EmailBar {
        "email": Email;
    }
    interface EmailList {
    }
    interface SideBar {
    }
    interface StarCheckbox {
        "value": boolean;
    }
    interface XIcon {
        "icon": IconDefinition;
        "mask"?: IconDefinition;
        "spin": boolean;
    }
}
declare global {
    interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {
    }
    var HTMLAppHeaderElement: {
        prototype: HTMLAppHeaderElement;
        new (): HTMLAppHeaderElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLCheckBoxElement extends Components.CheckBox, HTMLStencilElement {
    }
    var HTMLCheckBoxElement: {
        prototype: HTMLCheckBoxElement;
        new (): HTMLCheckBoxElement;
    };
    interface HTMLEmailBarElement extends Components.EmailBar, HTMLStencilElement {
    }
    var HTMLEmailBarElement: {
        prototype: HTMLEmailBarElement;
        new (): HTMLEmailBarElement;
    };
    interface HTMLEmailListElement extends Components.EmailList, HTMLStencilElement {
    }
    var HTMLEmailListElement: {
        prototype: HTMLEmailListElement;
        new (): HTMLEmailListElement;
    };
    interface HTMLSideBarElement extends Components.SideBar, HTMLStencilElement {
    }
    var HTMLSideBarElement: {
        prototype: HTMLSideBarElement;
        new (): HTMLSideBarElement;
    };
    interface HTMLStarCheckboxElement extends Components.StarCheckbox, HTMLStencilElement {
    }
    var HTMLStarCheckboxElement: {
        prototype: HTMLStarCheckboxElement;
        new (): HTMLStarCheckboxElement;
    };
    interface HTMLXIconElement extends Components.XIcon, HTMLStencilElement {
    }
    var HTMLXIconElement: {
        prototype: HTMLXIconElement;
        new (): HTMLXIconElement;
    };
    interface HTMLElementTagNameMap {
        "app-header": HTMLAppHeaderElement;
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "check-box": HTMLCheckBoxElement;
        "email-bar": HTMLEmailBarElement;
        "email-list": HTMLEmailListElement;
        "side-bar": HTMLSideBarElement;
        "star-checkbox": HTMLStarCheckboxElement;
        "x-icon": HTMLXIconElement;
    }
}
declare namespace LocalJSX {
    interface AppHeader {
    }
    interface AppHome {
    }
    interface AppProfile {
        "name"?: string;
    }
    interface AppRoot {
    }
    interface CheckBox {
        "value"?: boolean;
    }
    interface EmailBar {
        "email"?: Email;
    }
    interface EmailList {
    }
    interface SideBar {
    }
    interface StarCheckbox {
        "onToggled"?: (event: CustomEvent<boolean>) => void;
        "value"?: boolean;
    }
    interface XIcon {
        "icon"?: IconDefinition;
        "mask"?: IconDefinition;
        "spin"?: boolean;
    }
    interface IntrinsicElements {
        "app-header": AppHeader;
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "check-box": CheckBox;
        "email-bar": EmailBar;
        "email-list": EmailList;
        "side-bar": SideBar;
        "star-checkbox": StarCheckbox;
        "x-icon": XIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-header": LocalJSX.AppHeader & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "check-box": LocalJSX.CheckBox & JSXBase.HTMLAttributes<HTMLCheckBoxElement>;
            "email-bar": LocalJSX.EmailBar & JSXBase.HTMLAttributes<HTMLEmailBarElement>;
            "email-list": LocalJSX.EmailList & JSXBase.HTMLAttributes<HTMLEmailListElement>;
            "side-bar": LocalJSX.SideBar & JSXBase.HTMLAttributes<HTMLSideBarElement>;
            "star-checkbox": LocalJSX.StarCheckbox & JSXBase.HTMLAttributes<HTMLStarCheckboxElement>;
            "x-icon": LocalJSX.XIcon & JSXBase.HTMLAttributes<HTMLXIconElement>;
        }
    }
}
